### ISSUE TITLE
Plugin doesn't appear when installed

### ISSUE THREAD

**Issue by nathanchapman** [xatom-plugins/xatom-debug-nodejs#6]
Not showing up in the plugin browser window

**Comment by aneilbaboo** [comment]
I'm having the same problem.

Atom 1.18.0 x64 
macOS 10.12.5
nodeJs 8.1.4

**Comment by danmademe** [comment]
i fixed it by rebuilding the package from atom

**Comment by aneilbaboo** [comment]
Thanks @danmademe, that worked!

**Comment by quanru** [comment]
I'm having the same problem.

Atom 1.19.2 x64
macOS 10.12.6
nodeJs 8.2.1

**Comment by nathanchapman** [comment]
Thank you @danmademe!

**Comment by jmacmahon** [comment]
I'm having the same issue, but no little bug icon at the bottom right of the screen.

Atom 1.21.1 x64
macOS 10.12.6
node v8.5.0
